version: '3.8'

services:
  sbom-gen-web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./temp:/app/temp
    restart: unless-stopped